server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pethome?useUnicode=true&characterEncoding=UTF-8

mybatis:
  type-aliases-package: cn.xinhang.org.domain,cn.xinhang.org.query,
                        cn.xinhang.basic.domain,cn.xinhang.basic.query,
                        cn.xinhang.user.domain,cn.xinhang.user.query,

logging:
  level:
    root: debug
